### ISSUE TITLE
MDF export for vectors and bus signals

### ISSUE THREAD

**Issue by DavidKroeter** [rrahuldev/ExportMDF#1]
I have created a minimal example which creates a logsout structure with the following contents:
1) conventional signal
2) vector signal
3) bus signal *

It would be perfect if all types could be written to the *.dat file and afterwards processed with an analysis tool such as vSignalyzer.

_____
* All signals that are inside the bus shall be split up before being written to the *.dat file

Minimal example including an *.mdl file and the resulting *.mat file: [minimal_example.zip](https://github.com/rrahuldev/ExportMDF/files/3039004/minimal_example.zip)

**Comment by rrahuldev** [comment]
Thanks for the upload, David. I am working on it. I will push the update soon.

**Comment by rrahuldev** [comment]
@DavidKroeter I have pushed the update to master. Check with the latest script if you run into any issues.

**Comment by DavidKroeter** [comment]
Many thanks, @rrahuldev, for the quick fix! I will try as soon as I have time and come back to you.
