### ISSUE TITLE
Blocksize error during creation of *.dat file

### ISSUE THREAD

**Issue by DavidKroeter** [rrahuldev/ExportMDF#2]
Hello!

In the last issue that I filed (https://github.com/rrahuldev/ExportMDF/issues/1), you improved your code in such a way that my minimal example works now. However, if I try to convert a larger logsout structure, I get the following error
```
blocksize error DG
blocksize error CG
```

I looked into your code, but I cannot figure out why this happens. Do you have an explanation? The logsout file holds signals that originate from one huge bus, but essentially there is no difference to the minimal example.

Cheers,

David

Logsout structure:
[logsout.zip](https://github.com/rrahuldev/ExportMDF/files/3098991/logsout.zip)

**Comment by rrahuldev** [comment]
@DavidKroeter Thanks for testing the release and providing the zip file for the issue. I did push an update.  Check with the latest release if you run into the issue.

**Comment by DavidKroeter** [comment]
It works, thank you!
But only if I comment out the following part in _expMDF.m_:

```
flg_spacenames = contains(varnames, ' ');
% then replace with '_'
if any(flg_spacenames)
    spacenames = varnames(flg_spacenames);
    spacenames = cellfun(@(x) strrep(x, ' ','_'), spacenames, 'UniformOutput', false);
    varnames(flg_spacenames) = spacenames;
end
```

I had to replace it with to make it working (I'm on Matlab R2015b)

`varnames = strrep(varnames,' ','_');`
