### ISSUE TITLE
Group signals as array

### ISSUE THREAD

**Issue by DavidKroeter** [rrahuldev/ExportMDF#3]
Hello @rrahuldev !
Do you know the difference between *.dat and *.mdf files? I am asking because I have some measurement files in *.mdf format which have some vector signals included.
In my analysis toolbox (Vector vSignalyzer), I can see those vector signals as a separate group (see screenshot). Do you think this would be possible as well for *.dat files?
The advantange is that you can choose different plot layouts for vector formats in vSignalyzer.

![image](https://user-images.githubusercontent.com/49241066/58106451-6e9e2d80-7be8-11e9-968a-a57fd3256092.png)

1.) Vector signals (length = 250 elements each) "f_spdTrjOpenDrvl" and "f_spdTrjRollSagSummit"
2.) Standard one-dimensional signal "f_vehSpdEnhanced" with global data cursor set to 8m 4.9sec
3) Trajectory of "f_spdTrjOpenDrvl" at t = 8m 4.9sec

Cheers,

David

**Comment by DavidKroeter** [comment]
![image](https://user-images.githubusercontent.com/49241066/58106681-c2a91200-7be8-11e9-9198-0244cf5dbad2.png)

**Comment by rrahuldev** [comment]
Per format specification, we can group the signals.  For simplicity and general applicability, I have grouped all the signals under one group. We could try to expand the signals to multiple groups, but the question would be, on what basis should the signals be grouped, which applies to all conditions.

**Comment by DavidKroeter** [comment]
Hm, I see, we could run into a problem there if we don't follow a specific rule.

What about that:
--> Grouping would only be done for signals that are vector signals (dimension higher than 1)

All signals within such a vector would be named according to their dimension.
i.e. for a vector signal "signa1" with 3 dimensions, it would be 
signal1[01]
signal1[02]
signal1[03]

I think you are quite close a you already do the naming similarly instead of grouping those signals.

![image](https://user-images.githubusercontent.com/49241066/59360238-0991af80-8d30-11e9-97db-d7d86223880b.png)

**Comment by rrahuldev** [comment]
I do not work with Vector vSignalyzer, so it difficult to see how grouping is done or how it helps. 
Do you have a sample 'dat' file on how the grouping is done. I can probably work backwards to create grouping for vector signals..

**Comment by DavidKroeter** [comment]
I don't think that it is especially related to vSignalyzer as this is just the software I use for visualizing the traces. Measurements are taken with INCA or any other tool. Nevertheless, I attached a sample file (unfortunately, I only have one as *.mdf format) for you which might help.
[sampleData.zip](https://github.com/rrahuldev/ExportMDF/files/3395746/sampleData.zip)

**Comment by rrahuldev** [comment]
David, I have pushed changes to "features/signal_grouping" branch for testing.  The update includes only renaming vector signals to zero based index.  Could you check if it works the way you expect with your data. Thanks!

**Comment by DavidKroeter** [comment]
I have tested your changes and for me it looks very good. If it's also ok for you, you can pull your changes into the master branch. Thanks for your work!

**Comment by rrahuldev** [comment]
Thanks for testing. Merged changes to master.
